//Teste de requisição - categorias
@baseURL=http://localhost:4000

@id=60b0ef4c72075c00fef63001

@nome=salto

###
//GET - lista os items
GET {{baseURL}}/items
Content-Type: application/json

###
//GET - lista os items pelo nome
GET {{baseURL}}/items/{{nome}}
Content-Type: application/json

###
//Post - inclue um novo item
POST {{baseURL}}/items
Content-Type: application/json

{
    "nome": "tenis",
    "categoria": "60ad08e748e9e2048d20c1c2", 
    "quantidade": "5",
    "status": "disponivel",
    "foto":{
        "originalname": "tenis",
        "path": "/public/upload/tenis.jpg",
        "size": "240",
        "mimeType": "tenis/jpg"
    },
    "nota": "4",
    "preco": "53"
}

###
//DELETE apaga um item
DELETE {{baseURL}}/items/{{id}}
Content-Type: application/json

###
//PUT altera um item
PUT {{baseURL}}/items
Content-Type: application/json

{
    "_id":"60b11425685f71067cca25a8",
    "nome": "salto",
    "categoria": "60b11425685f71067cca25a8", 
    "quantidade": "",
    "status": "disponivel",
    "foto": {
        "originalname": "",
        "path": "",
        "size": "",
        "mimeType": ""
    },
    "nota": "",
    "preço": ""
}